import Head from "next/head";
import { FC } from "react";
import Footer from "./footer";
import Navigation from "./navigation";

const Container: FC = ({ children }) => {
    return (
        <div className="min-h-screen bg-gray-100">
            <Head>
                <title>Habemus le Clubé</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="h-screen flex flex-col justify-between">
                <Navigation />

                {/* container px-5 py-5 mx-auto mb-auto md:py-20 */}
                <div className="container mx-auto mb-auto p-4">{children}</div>

                <Footer />
            </div>
        </div>
    );
};

export default Container;
