import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
    return (
        <div className="min-h-screen bg-gray-100">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <h1>Hello NextJs</h1>

            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
        </div>
    )
}

export default Home
